### ISSUE TITLE
Cannot change user's first and last name from the admin interface. 

### ISSUE THREAD

**Issue by Nikita1710** [Fifty50STEMM/mentorship.fifty50.org.au#4]
The app http://fifty50.pythonanywhere.com/admin/users/user/ doesn't update the first and last name. It reverts back to the original name entered when signing up. It does change the preferred name of that particular user.

**Comment by elena** [comment]
It may relate to this error message:

`2018-02-24 15:20:48,712: Internal Server Error: /profile/~update/#012Traceback (most recent call last):#012  File "/home/fifty50/.virtualenvs/fifty50/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner#012    response = get_response(request)#012  File "/home/fifty50/.virtualenvs/fifty50/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response#012    response = self.process_exception_by_middleware(e, request)#012  File "/home/fifty50/.virtualenvs/fifty50/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response#012    response = wrapped_callback(request, *callback_args, **callback_kwargs)#012  File "/home/fifty50/.virtualenvs/fifty50/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view#012    return self.dispatch(request, *args, **kwargs)#012  File "/home/fifty50/.virtualenvs/fifty50/lib/python3.6/site-packages/django/contrib/auth/mixins.py", line 56, in dispatch#012    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)#012  File "/home/fifty50/.virtualenvs/fifty50/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch#012    return handler(request, *args, **kwargs)#012  File "/home/fifty50/.virtualenvs/fifty50/lib/python3.6/site-packages/django/views/generic/edit.py", line 236, in get#012    return super(BaseUpdateView, self).get(request, *args, **kwargs)#012  File "/home/fifty50/.virtualenvs/fifty50/lib/python3.6/site-packages/django/views/generic/edit.py", line 174, in get#012    return self.render_to_response(self.get_context_data())#012  File "/home/fifty50/.virtualenvs/fifty50/lib/python3.6/site-packages/django/views/generic/edit.py", line 93, in get_context_data#012    kwargs['form'] = self.get_form()#012  File "/home/fifty50/.virtualenvs/fifty50/lib/python3.6/site-packages/django/views/generic/edit.py", line 44, in get_form#012    form_class = self.get_form_class()#012  File "/home/fifty50/.virtualenvs/fifty50/lib/python3.6/site-packages/django/views/generic/edit.py", line 132, in get_form_class#012    return model_forms.modelform_factory(model, fields=self.fields)#012  File "/home/fifty50/.virtualenvs/fifty50/lib/python3.6/site-packages/django/forms/models.py", line 563, in modelform_factory#012    return type(form)(class_name, (form,), form_class_attrs)#012  File "/home/fifty50/.virtualenvs/fifty50/lib/python3.6/site-packages/django/forms/models.py", line 277, in __new__#012    raise FieldError(message)#012django.core.exceptions.FieldError: Unknown field(s) (name) specified for User`
